--- 
title: "Data Science for Kids"
author: "Haim Bar, HaiYing Wang, and Jun Yan"
date: "`r Sys.Date()`"
output: pdf_document
documentclass: krantz
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
fontsize: 12pt, krantz2
monofont: Source Code Pro
monofontoptions: Scale=0.85
link-citations: yes
colorlinks: yes
description: This is an introduction of data science for kids with hands-on simulation
  experiments. Early materials were prepared for a pre-college camp in summer 2021
  at UConn.
site: bookdown::bookdown_site
---

# Styles for ourselves {-}

Basic template for R Markdown from Wenjie Wang
[at Stat Data Science Lab](https://statds.org/template/) with
[source](https://github.com/statds/dslab-templates/).

+ Keep line width under 80 characters for tidy source view.
+ No labeling equations unless references.
+ Cross-references labels
    - chapters: `ch:estimation`; Chapter~\@ref{ch:estimation}
	- equations: `eq:area`
	- tables: `tab:simu`
	- figures: `fig:normhist`
+ R chunk lables: include chapter index to avoid unwanted duplicates
+ Index when appropriate for key words.



# Preface {-}

## Who this book is for {-}
This book is the product of our efforts to promote data science among
high school students. 

Many interesting points ...

## How to read this book {-}

Some chapters can be skipped ...

## Computing language {-}

We use R because ...

## About the authors {-}

**Haim Bar** is an Associate Professor in the Department of Statistics,
University of Connecticut. He does a lof of interesting things ...


**HaiYing Wang** is an Associate Professor in the Department of Statistics,
University of Connecticut. He does a lof of interesting things ...


**Jun Yan** is a Professor in the Department of Statistics,
University of Connecticut. He does a lof of interesting things ...


All three authors have been members of the Computer Committee of the Department
for years, during which time the idea of the book emerged.


# Prerequisites {-}

We hope the widest accessibility.

<!-- This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$. -->

<!-- The **bookdown** package can be installed from CRAN or Github: -->

<!-- ```{r eval=FALSE} -->
<!-- install.packages("bookdown") -->
<!-- # or the development version -->
<!-- # devtools::install_github("rstudio/bookdown") -->
<!-- ``` -->

<!-- Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`. -->

To compile this example to PDF, you need XeLaTeX. You are recommended to install
TinyTeX\index{TinyTex} (which includes XeLaTeX): <https://yihui.org/tinytex/>.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
    .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```



<!-- For use only in PDF, is skipped in HTML -->
\mainmatter
