<<probability-Simpson, eval=TRUE, >>=
set.seed(2021)
g <- 4 # number of groups
n <- 40 # number of instances in each group
z <- rep(1:4, each=n) # grouping variable
x <- runif(n*g, 0, 2) + z # x variable that depends on z
y <- 2 * z - x + rnorm(n*g) # y variable that depends on x and z
plot(x, y) # plot the whole data
plot(x, y, pch=rep(1:g, each=n), col=rep(1:g, each=n))
# label the points for different groups
@