on:
  push:
    branches:
      - main
      - master

name: knit

jobs:
  knit:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-tinytex@v1

      - name: Install fonts
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | /usr/bin/sudo debconf-set-selections
          /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ttf-mscorefonts-installer fonts-inconsolata
          fc-cache -fv
          fc-list : family | sort

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install R packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Compile Rnw/LaTeX to PDF
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          make -C book pdf
          git remote set-branches origin gh-pages
          git fetch origin gh-pages
          mkdir .gh-pages
          git worktree add --track -B gh-pages .gh-pages origin/gh-pages
          rm -rf .gh-pages/*
          cp -v book/main.pdf .gh-pages
          cd .gh-pages
          git add -A .
          git commit --allow-empty -m "GHA for $GITHUB_SHA"
          git push origin gh-pages
          git worktree remove .gh-pages
          rm -rf .gh-pages
